config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      registrations:  'registrations'
  }
  get 'comments/to/:post_id' =>'comments#new', :as => 'new_comment_from_post'
  resources :comments
  resources :posts
  resources :profiles
  resources :users
  get 'friendships' => 'friendships#index', :as => 'friendships'
  get 'friends_of' => 'friendships#friends_of'
  get 'friends_of/:id' => 'friendships#friends_of'
  post 'friendships/:id/accept' => 'friendships#accept', :as => 'friendship_accept'
  post 'friendships/:id/declined' => 'friendships#remove_friend', :as => 'friendship_declined'
  post 'friendships/:id/remove_request' => 'friendships#remove_friend', :as => 'friendship_remove_request'
  post 'friendships/:id/remove_friend' => 'friendships#remove_friend', :as => 'friendship_remove_friend'
  post 'friendships/:id/send_request' => 'friendships#send_request', :as => 'friendship_send_request'
  get 'home' => 'profiles#wall'
  get 'profile' => 'profiles#wall'
  get 'profile/:id' => 'profiles#wall', :as => 'wall_profile'
  post 'profile/:post_id/like' => 'profiles#like', :as => 'like_post'

  post 'images' => 'images#upload'
  root 'profiles#wall'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  acts_as_liker
  belongs_to :user
  has_many :posts
  has_many :friendships
  has_many :friendships_to, :class_name => 'Friendship',:foreign_key => 'profile1_id'
  has_many :friends, -> { where 'friendships.state'=> 1 }, :class_name => 'Profile', through: :friendships, :source => :profile1
  has_one :image, as: :attachment
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def wall
    # asd =current_user
    # byebug
    if(params[:id])
      @profile = Profile.find(params[:id])
    else
      @profile = current_user.profile
    end
    if (@profile)
      @posts = Post.where(:profile =>@profile.friends.to_a << @profile).order(created_at: :desc)
    else
      @posts = [];
    end
    respond_to do |format|
      format.json { render :json => {
            posts:@posts.to_json(
                :only=>[:id,:message,:created_at,:likers_count],
                :include=>{
                    :profile=>{
                        :only => [:id,:firstname,:surname],
                        :include=>{
                            :image=>{:methods => :content_url}}},
                    :comments=>{
                        :only => [:message,:created_at],
                        :include=>{
                            :profile =>{
                                :only => [:id,:firstname,:surname],
                                :include=>{
                                    :image=>{:methods => :content_url}}
                            }
                        }
                    }
                }
            ),
            profile:@profile.to_json(
                :only => [:id,:firstname,:surname],
                :include=>{
                    :image=>{:methods => :content_url}}
            ),
            owner: current_user.profile.id == @profile.id
      }}
      format.html { render :wall }
    end
  end
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    filtered_data = profile_params
    pp = filtered_data

    # byebug
    if(filtered_data['firstname']&&filtered_data['image'])
      image = Image.create({:name=> filtered_data['firstname'], :content=> filtered_data['image']})
      pp['image'] = image
    end
    if(params['image_id'])
      pp['image'] = Image.find(params['image_id']);
    end
    # byebug
    respond_to do |format|
      if @profile.update(pp)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    current_user.profile.like!(Post.find(params['post_id']))
    np = Post.find(params['post_id'])
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render :json => np.likers_count}
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :surname, :age, :gender, :birday,:image,:image_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birday %><br>
    <%= f.text_field :birday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Surname</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Birday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.surname %></td>
        <td><%= profile.age %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.birday %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @profile.surname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Birday:</strong>
  <%= @profile.birday %>
</p>
<%= link_to 'Home', root_path %>
|
<%= link_to 'Edit', edit_profile_path(@profile) %>

app/views/profiles/wall.html.erb
<%= link_to 'home', root_path %>
<%= link_to 'edit my profile', edit_profile_path(:id => @profile_login.id)  %>
<%= link_to 'logout', destroy_user_session_path, :method=>'delete'  %>
<%= link_to 'new post', new_post_path %>
<%= link_to 'friendships', friendships_path %>
<h2><%= @profile.firstname + ' ' + @profile.surname %></h2>
<%= image_tag @profile.image.content.url(:thumb) if @profile.image %>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.profile.firstname,wall_profile_path(post.profile) %>: <%= post.message %>. <%= link_to 'I like ('+post.likers_count.to_s+')', like_post_path(:post_id => post.id),:method=> 'Post' %>. <%= link_to 'Add Comment', new_comment_from_post_path(:post_id => post.id) %></li>
      <% if post.comments %>
      <ul>
        <% post.comments.each do |comment| %>
                <li><%= link_to comment.profile.firstname,wall_profile_path(comment.profile) %>: <%= comment.message %></li>
        <% end %>
       </ul>
      <% end %>
  <% end %>
</ul>