config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      registrations:  'registrations'
  }
  get 'comments/to/:post_id' =>'comments#new', :as => 'new_comment_from_post'
  resources :comments
  resources :posts
  resources :profiles
  resources :users
  get 'friendships' => 'friendships#index', :as => 'friendships'
  get 'friends_of' => 'friendships#friends_of'
  get 'friends_of/:id' => 'friendships#friends_of'
  post 'friendships/:id/accept' => 'friendships#accept', :as => 'friendship_accept'
  post 'friendships/:id/declined' => 'friendships#remove_friend', :as => 'friendship_declined'
  post 'friendships/:id/remove_request' => 'friendships#remove_friend', :as => 'friendship_remove_request'
  post 'friendships/:id/remove_friend' => 'friendships#remove_friend', :as => 'friendship_remove_friend'
  post 'friendships/:id/send_request' => 'friendships#send_request', :as => 'friendship_send_request'
  get 'home' => 'profiles#wall'
  get 'profile' => 'profiles#wall'
  get 'profile/:id' => 'profiles#wall', :as => 'wall_profile'
  post 'profile/:post_id/like' => 'profiles#like', :as => 'like_post'

  post 'images' => 'images#upload'
  root 'profiles#wall'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :profile
  belongs_to :profile1, class_name: 'Profile', foreign_key: 'profile1_id'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    current_profile = current_user.profile
    @friendships = current_profile.friends
    @all_friends = Friendship.where("profile_id = :cprofile OR (profile1_id = :cprofile AND state = 0)",{:cprofile=> current_profile.id})
    @not_friends = Profile.where.not(:id => @friendships.to_a << current_profile)
    # byebug
    respond_to do |format|
      format.json {
        render :json => {
            :all_friends => @all_friends.to_json(
              :include=>{
                  :profile1=>{
                      :only => [:id,:firstname,:surname],
                      :include=>{
                          :image=>{:methods => :content_url}}},
                  :profile=>{
                      :only => [:id,:firstname,:surname],
                      :include=>{
                          :image=>{:methods => :content_url}}}}),
            :not_friends => @not_friends.to_json(
               :only => [:id,:firstname,:surname],
                  :include=>{
                       :image=>{:methods => :content_url}}),
            :current_profile=> current_profile.id}
      }
      format.html {render index}
    end
  end
  def accept
    f = Friendship.find(params[:id])
    f.state = 1
    f.save
    nf = Friendship.create(:profile => current_user.profile,:profile1 => f.profile,:state=>1)

    respond_to do |format|
      format.json { render :json => nf.to_json(
          :include=>{
              :profile1=>{
                  :only => [:id,:firstname,:surname],
                  :include=>{
                      :image=>{:methods => :content_url}}},
              :profile=>{
                  :only => [:id,:firstname,:surname],
                  :include=>{
                      :image=>{:methods => :content_url}}}}
      )}
      format.html {redirect_to friendships_path}
    end
  end
  def remove_friend
    Friendship.find(params[:id]).destroy
    respond_to do |format|
      format.json { render :json => {}}
      format.html {redirect_to friendships_path}
    end
  end
  def send_request
    f = Friendship.create(:profile => current_user.profile,:profile1_id => params[:id],:state=>0)
    respond_to do |format|
      format.json { render :json => {id:f.id}}
      format.html {redirect_to friendships_path}
    end
  end
  def friends_of
    if (params[:id])
      id = params[:id]
    else
      id = current_user.profile.id
    end
    @all_friends = Friendship.where("profile_id = :cprofile AND state = 1",{:cprofile=> id})
    respond_to do |format|
      format.json {
        render :json => @all_friends.to_json(
          :include=>{
              :profile1=>{
                  :only => [:id,:firstname,:surname],
                  :include=>{
                      :image=>{:methods => :content_url}}}
          }
        )
      }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<h3>All</h3>
<ul>

  <% show = []
     if @all_friends
       @all_friends.each do |friendship|%>
          <%  if (friendship.profile == current_user.profile)
                show << friendship.profile1.id %>
                <li><%= link_to friendship.profile1.firstname,wall_profile_path(friendship.profile1) %>
                <% if(friendship.state == 0) %>
                    <%= link_to 'Remove request', friendship_remove_request_path(friendship), :method => 'post' %>
                <% else %>
                    <%= link_to 'Remove friend', friendship_remove_friend_path(friendship), :method => 'post' %>
                <% end %>
                </li>
          <% else
                show << friendship.profile.id %>
                <li>
                    <%= link_to friendship.profile.firstname,wall_profile_path(friendship.profile) %>
                    <%= link_to 'Accept', friendship_accept_path(friendship), :method => 'post' %>
                    <%= link_to 'Declined', friendship_declined_path(friendship), :method => 'post' %>
                </li>
          <% end %>
      <% end
         end%>

  <%
     if @not_friends
       @not_friends.each do |profile|
         if(!show.include?(profile.id)) %>
            <li>
              <%= link_to profile.firstname,wall_profile_path(profile) %>
              <%= link_to 'Send request', friendship_send_request_path(profile), :method => 'post' %>
            </li>
      <% end
       end
     end %>
</ul>
<%= link_to 'Home', root_path %>